### ISSUE TITLE
white-space and non-latin characters cause malfunction

### ISSUE THREAD

**Issue by zmn-hamid** [zmn-hamid/Aseprite-Export-Video-Script#2]
Bellow is the original comment. I was able to reproduce the encoding bug, but not the white spaces bug. Files and folders with white spaces worked fine for me, but I also noticed in the log that when the encoding bug happens, the full path of the concat file is also cut off from where there is a white space. And unfortunately I couldn't find any fix for this. Lua is a headache.

Regarding the encoding, I found out the when running the command manually, the command works perfectly. You have to also run `chcp 65001` before running that, to change the encoding of the current CMD instance. I tried mimicking this behavior and added the mentioned command before the FFMPEG command but it made no changes. Leaving this issue here in case anyone could fix it

              Hi, I did everything as written in the README and it works. It runs even if there are frames with different duration. But it gives an error if there are spaces in the file path in the folder name or the name is not in Latin. Anyway, everything works.

_Originally posted by @Zakhar201 in https://github.com/zmn-hamid/Aseprite-Export-Video-Script/issues/1#issuecomment-2351106716_

**Comment by Zakhar201** [comment]
Hi, I tried different ways to save my projects and ran into a problem: If there are numbers in the file name in the file path, the program doesn't work
Correction: works ONLY WITH PNG FILE NUMBER AFTER SAVING TO PNG

**Comment by zmn-hamid** [comment]
> Hi, I tried different ways to save my projects and ran into a problem: If there are numbers in the file name in the file path, the program doesn't work Correction: works ONLY WITH PNG FILE NUMBER AFTER SAVING TO PNG

Hi Zakhar. Thank you for your information. I posted a new update to the script recently that solved all these problems. Make sure to check out [README.md](https://github.com/zmn-hamid/Aseprite-Export-Video-Script/blob/master/README.md) and download the newest version of [Export Video.lua](https://github.com/zmn-hamid/Aseprite-Export-Video-Script/blob/master/Export%20Video.lua) file. Have a nice day/night

**Comment by zmn-hamid** [comment]
Closing this issue due to [this commit](https://github.com/zmn-hamid/Aseprite-Export-Video-Script/commit/4df3b6632a4f30505542dbec10a8380038c48852) and fixing/handling of the problems
